server:
  port: 8090
  servlet:
    context-path: /
    session:
      cookie:
        http-only: true

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/czb?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: root

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  global-config:
    db-config:
      # 主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (idWorker)", UUID:"全局唯一ID (UUID)";
      id-type: AUTO
      # 字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      insert-strategy: NOT_NULL
      update-strategy: NOT_NULL
      # 是否开启大写命名
      capital-mode: false
      # 逻辑已删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

# 热修复
hotFix:
  enable: true
  base-package: czb.framework.hotfix.demo
  load-path: E:\Project\Java\OpenSource\czb-spring-hotfix\czb-spring-hotfix-demo\hotfix
  should-load-in-app-classLoader-package:
    - czb.framework.hotfix.demo.entity
    - czb.framework.hotfix.demo.vo.resq